name: Build and Deploy node Python Django app to Azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "testappgoinazure"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7.5'                # set this to the python version to use
  RESOURCEGROUPNAME: "testpythonapp123-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "testpythonapp123-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"
  DATABASEACCOUNTID: ""
  DATABASEACCOUNTLOCATION: ""

jobs:
  Build:
    name: Build and Run tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
       go-version: '1.10'
    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates
        cd Application
        go get -d
        go build -o ..\buildartifacts\${{ env.AZURE_WEBAPP_NAME }}.exe
        cp web.config ..\buildartifacts\web.config
    # Uploading application to artifact store
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts
    # Uploading Arm Template to artifact store
    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: ArmTemplates
  Deploy:
    name: Deploy to azure web app
    needs: Build
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: Application
  # Downloading Arm Template
    - name: Download Arm Template
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: deploymenttemplates
        path: ArmTemplates
    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy ARM Template
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      continue-on-error: false
      with:
        inlineScript: |
          az group create --name "${{ env.RESOURCEGROUPNAME }}" --location "${{ env.LOCATION }}"
          az deployment group create --resource-group "${{ env.RESOURCEGROUPNAME }}" --template-file ./ArmTemplates/windows-webapp-template.json --parameters webAppName="${{ env.AZURE_WEBAPP_NAME }}" hostingPlanName="${{ env.HOSTINGPLANNAME }}" appInsightsLocation="${{ env.APPINSIGHTLOCATION }}" sku="${{ env.SKU }}"
    # Deploy web app
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
